import { useState, useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'

const EMOJIS: { emoji: string; keywords: string[] }[] = [
  // Faces — positive
  { emoji: '😀', keywords: ['grinning', 'happy', 'smile', 'grin', 'joy'] },
  { emoji: '😁', keywords: ['beaming', 'grin', 'happy', 'excited', 'teeth'] },
  { emoji: '😂', keywords: ['laugh', 'crying laughing', 'funny', 'lol', 'haha', 'joy', 'tears'] },
  { emoji: '🤣', keywords: ['rofl', 'rolling laugh', 'hilarious', 'floor', 'lol'] },
  { emoji: '😊', keywords: ['smile', 'happy', 'blush', 'pleased', 'friendly', 'warm'] },
  { emoji: '😇', keywords: ['innocent', 'angel', 'halo', 'pure', 'good'] },
  { emoji: '🥰', keywords: ['smiling hearts', 'love', 'adore', 'cute', 'affection', 'smitten'] },
  { emoji: '😍', keywords: ['heart eyes', 'love', 'amazing', 'adore', 'beautiful', 'wow'] },
  { emoji: '🤩', keywords: ['star struck', 'excited', 'wow', 'amazing', 'celebrity', 'star eyes'] },
  { emoji: '😘', keywords: ['kiss', 'blow kiss', 'love', 'affection', 'flirt'] },
  { emoji: '😗', keywords: ['kiss', 'whistle', 'pucker'] },
  { emoji: '😙', keywords: ['kiss smiling', 'happy kiss', 'cute'] },
  { emoji: '🥲', keywords: ['sad smile', 'happy cry', 'bittersweet', 'touched', 'grateful'] },
  { emoji: '😚', keywords: ['kiss closed eyes', 'love', 'blush'] },
  { emoji: '😋', keywords: ['yummy', 'delicious', 'tasty', 'savoring', 'lick'] },
  { emoji: '😛', keywords: ['tongue', 'playful', 'silly', 'tease'] },
  { emoji: '😜', keywords: ['wink tongue', 'silly', 'joking', 'playful', 'crazy'] },
  { emoji: '🤪', keywords: ['zany', 'crazy', 'wild', 'wacky', 'silly', 'goofy'] },
  { emoji: '😝', keywords: ['squint tongue', 'gross', 'yuck', 'naughty'] },
  { emoji: '🤑', keywords: ['money mouth', 'rich', 'dollar', 'cash', 'profit'] },
  { emoji: '😎', keywords: ['cool', 'sunglasses', 'awesome', 'stylish', 'confident', 'swag'] },
  { emoji: '🥸', keywords: ['disguise', 'glasses', 'incognito', 'spy', 'nerdy'] },
  { emoji: '🤓', keywords: ['nerd', 'geek', 'smart', 'glasses', 'studious'] },
  { emoji: '🧐', keywords: ['monocle', 'curious', 'inspect', 'examine', 'fancy', 'investigate'] },
  { emoji: '🤭', keywords: ['giggle', 'oops', 'quiet', 'secret', 'shh', 'surprised'] },
  { emoji: '🫢', keywords: ['gasp', 'shocked', 'surprised', 'wow', 'eyes wide'] },
  { emoji: '🫣', keywords: ['peek', 'nervous', 'shy', 'hide', 'look'] },
  { emoji: '🤫', keywords: ['shush', 'quiet', 'secret', 'shhh', 'hush'] },
  { emoji: '🤔', keywords: ['thinking', 'hmm', 'consider', 'wondering', 'ponder', 'maybe'] },
  { emoji: '🫠', keywords: ['melting', 'awkward', 'embarrassed', 'oops', 'dissolve'] },
  { emoji: '🤐', keywords: ['zip mouth', 'silent', 'secret', 'quiet', 'zipper', 'no comment'] },
  { emoji: '🤨', keywords: ['raised eyebrow', 'suspicious', 'skeptical', 'doubtful', 'really'] },
  { emoji: '😐', keywords: ['neutral', 'blank', 'meh', 'unimpressed', 'deadpan'] },
  { emoji: '😑', keywords: ['expressionless', 'blank', 'done', 'over it', 'meh'] },
  { emoji: '😶', keywords: ['no mouth', 'silent', 'speechless', 'blank'] },
  { emoji: '😏', keywords: ['smirk', 'sly', 'smug', 'knowing', 'cunning'] },
  { emoji: '😒', keywords: ['unamused', 'whatever', 'side eye', 'unhappy', 'bored'] },
  { emoji: '🙄', keywords: ['eye roll', 'whatever', 'unimpressed', 'sarcastic', 'rolling eyes', 'ugh'] },
  { emoji: '😬', keywords: ['grimace', 'awkward', 'nervous', 'cringe', 'oops', 'yikes'] },
  { emoji: '🤥', keywords: ['lying', 'liar', 'pinocchio', 'nose', 'dishonest'] },
  { emoji: '😌', keywords: ['relieved', 'peaceful', 'calm', 'satisfied', 'content'] },
  { emoji: '😔', keywords: ['pensive', 'sad', 'thoughtful', 'sorry', 'regret'] },
  { emoji: '😪', keywords: ['sleepy', 'tired', 'drowsy', 'snot bubble', 'asleep'] },
  { emoji: '🤤', keywords: ['drool', 'yummy', 'hungry', 'food', 'delicious'] },
  { emoji: '😴', keywords: ['sleeping', 'zzz', 'tired', 'asleep', 'snore', 'rest'] },
  // Faces — negative / intense
  { emoji: '😫', keywords: ['tired', 'exhausted', 'frustrated', 'weary', 'done'] },
  { emoji: '😩', keywords: ['weary', 'tired', 'done', 'exhausted', 'fed up'] },
  { emoji: '🥺', keywords: ['pleading', 'puppy eyes', 'begging', 'please', 'sad cute'] },
  { emoji: '😢', keywords: ['cry', 'sad', 'tear', 'unhappy', 'disappointed', 'upset'] },
  { emoji: '😭', keywords: ['crying', 'sob', 'sad', 'tears', 'upset', 'weep', 'bawling'] },
  { emoji: '😤', keywords: ['frustrated', 'angry', 'annoyed', 'steam', 'huff', 'triumph'] },
  { emoji: '😠', keywords: ['angry', 'mad', 'annoyed', 'cross', 'grumpy'] },
  { emoji: '😡', keywords: ['angry', 'mad', 'furious', 'rage', 'red', 'pouting'] },
  { emoji: '🤬', keywords: ['swearing', 'angry', 'cursing', 'mad', 'furious', 'symbols'] },
  { emoji: '😈', keywords: ['devil', 'evil', 'mischief', 'naughty', 'horns', 'villain'] },
  { emoji: '👿', keywords: ['angry devil', 'evil', 'mad', 'horns', 'rage'] },
  { emoji: '💀', keywords: ['skull', 'dead', 'death', 'dying', 'bones', 'danger', 'poison'] },
  { emoji: '☠️', keywords: ['skull crossbones', 'dead', 'poison', 'danger', 'pirate'] },
  { emoji: '😱', keywords: ['scream', 'horror', 'scared', 'shock', 'terrified', 'fear'] },
  { emoji: '😨', keywords: ['fearful', 'scared', 'worried', 'frightened', 'anxious'] },
  { emoji: '😰', keywords: ['anxious sweat', 'nervous', 'worried', 'stressed', 'cold sweat'] },
  { emoji: '😥', keywords: ['disappointed relieved', 'sad', 'sweat', 'phew', 'sigh'] },
  { emoji: '😓', keywords: ['downcast sweat', 'hard work', 'effort', 'struggle', 'stress'] },
  { emoji: '🤯', keywords: ['mind blown', 'exploding head', 'shocked', 'wow', 'unbelievable', 'amazing'] },
  { emoji: '😮', keywords: ['surprised', 'wow', 'open mouth', 'shock', 'gasp', 'whoa'] },
  { emoji: '😲', keywords: ['astonished', 'shocked', 'wow', 'amazed', 'stunned'] },
  { emoji: '🥵', keywords: ['hot', 'sweating', 'heat', 'fever', 'warm', 'overheated'] },
  { emoji: '🥶', keywords: ['cold', 'freezing', 'shivering', 'frozen', 'chilly', 'blue'] },
  { emoji: '😷', keywords: ['mask', 'sick', 'ill', 'medical', 'covid', 'flu'] },
  { emoji: '🤒', keywords: ['sick', 'fever', 'ill', 'thermometer', 'unwell'] },
  { emoji: '🤕', keywords: ['hurt', 'injured', 'bandage', 'accident', 'ouch'] },
  { emoji: '🤢', keywords: ['nauseous', 'sick', 'gross', 'eww', 'ill', 'vomit'] },
  { emoji: '🤮', keywords: ['vomit', 'sick', 'gross', 'puke', 'disgusting'] },
  { emoji: '🤧', keywords: ['sneeze', 'cold', 'sick', 'tissue', 'flu', 'ill'] },
  { emoji: '😵', keywords: ['dizzy', 'dead eyes', 'confused', 'spiral', 'faint'] },
  { emoji: '🥴', keywords: ['woozy', 'drunk', 'confused', 'dizzy', 'tipsy'] },
  { emoji: '😴', keywords: ['sleep', 'zzz', 'tired', 'rest', 'snore'] },
  { emoji: '😅', keywords: ['sweat smile', 'nervous', 'awkward', 'phew', 'relieved', 'close call'] },
  // Faces — special
  { emoji: '🤡', keywords: ['clown', 'joke', 'silly', 'circus', 'foolish'] },
  { emoji: '👹', keywords: ['ogre', 'monster', 'devil', 'red', 'scary', 'japanese'] },
  { emoji: '👺', keywords: ['goblin', 'evil', 'red', 'angry', 'japanese', 'monster'] },
  { emoji: '👻', keywords: ['ghost', 'halloween', 'boo', 'spooky', 'spirit'] },
  { emoji: '👾', keywords: ['alien monster', 'game', 'pixel', 'space invader', 'retro'] },
  { emoji: '🤖', keywords: ['robot', 'machine', 'android', 'ai', 'tech', 'bot'] },
  // Gestures & hands
  { emoji: '👍', keywords: ['thumbs up', 'like', 'good', 'yes', 'approve', 'great', 'plus'] },
  { emoji: '👎', keywords: ['thumbs down', 'dislike', 'no', 'bad', 'disapprove', 'minus'] },
  { emoji: '👌', keywords: ['ok', 'okay', 'perfect', 'good', 'fine', 'chef kiss'] },
  { emoji: '🤌', keywords: ['pinched fingers', 'chef kiss', 'italian', 'perfect', 'question'] },
  { emoji: '✌️', keywords: ['peace', 'victory', 'two fingers', 'v sign', 'scissors'] },
  { emoji: '🤞', keywords: ['fingers crossed', 'luck', 'hope', 'wish', 'cross fingers'] },
  { emoji: '🤟', keywords: ['love you', 'sign language', 'rock', 'hand', 'ily'] },
  { emoji: '🤘', keywords: ['rock on', 'metal', 'horns', 'rock', 'music'] },
  { emoji: '🤙', keywords: ['call me', 'hang loose', 'shaka', 'phone', 'hawaii'] },
  { emoji: '👈', keywords: ['point left', 'direction', 'that way', 'left', 'indicate'] },
  { emoji: '👉', keywords: ['point right', 'direction', 'this way', 'right', 'indicate'] },
  { emoji: '👆', keywords: ['point up', 'direction', 'above', 'up', 'number one'] },
  { emoji: '👇', keywords: ['point down', 'below', 'down', 'direction', 'indicate'] },
  { emoji: '☝️', keywords: ['index up', 'one', 'point', 'first', 'important'] },
  { emoji: '✋', keywords: ['raised hand', 'stop', 'high five', 'halt', 'five'] },
  { emoji: '🤚', keywords: ['raised back hand', 'stop', 'five', 'high five'] },
  { emoji: '🖐️', keywords: ['hand splayed', 'five', 'stop', 'hi', 'spread'] },
  { emoji: '🖖', keywords: ['vulcan salute', 'spock', 'star trek', 'live long', 'peace'] },
  { emoji: '👋', keywords: ['wave', 'hello', 'hi', 'bye', 'goodbye', 'greet'] },
  { emoji: '🤙', keywords: ['call', 'shaka', 'hang loose'] },
  { emoji: '💪', keywords: ['strong', 'muscle', 'flex', 'power', 'strength', 'bicep', 'buff'] },
  { emoji: '🦾', keywords: ['mechanical arm', 'prosthetic', 'strong', 'bionic', 'robot'] },
  { emoji: '🖕', keywords: ['middle finger', 'rude', 'offensive', 'angry', 'gesture'] },
  { emoji: '✍️', keywords: ['writing', 'pen', 'edit', 'sign', 'note', 'author'] },
  { emoji: '🤝', keywords: ['handshake', 'agreement', 'deal', 'partners', 'shake', 'meeting'] },
  { emoji: '🙌', keywords: ['hands up', 'praise', 'celebration', 'high five', 'clap', 'hooray'] },
  { emoji: '👏', keywords: ['clap', 'applause', 'bravo', 'well done', 'clapping', 'praise'] },
  { emoji: '🫶', keywords: ['heart hands', 'love', 'care', 'support', 'together'] },
  { emoji: '🙏', keywords: ['pray', 'please', 'thank you', 'hope', 'namaste', 'hands together', 'thanks'] },
  { emoji: '🤲', keywords: ['palms up', 'open hands', 'receive', 'offer', 'give'] },
  { emoji: '👐', keywords: ['open hands', 'jazz hands', 'hug', 'receive', 'present'] },
  { emoji: '🫶', keywords: ['heart hands', 'love', 'care', 'unity', 'together'] },
  { emoji: '🫱', keywords: ['hand right', 'rightward', 'reach', 'offer'] },
  { emoji: '🫲', keywords: ['hand left', 'leftward', 'reach', 'offer'] },
  { emoji: '💅', keywords: ['nail polish', 'sassy', 'fabulous', 'manicure', 'beauty'] },
  { emoji: '👂', keywords: ['ear', 'listen', 'hear', 'audio', 'sound'] },
  { emoji: '👃', keywords: ['nose', 'smell', 'sniff', 'scent'] },
  { emoji: '👁️', keywords: ['eye', 'look', 'see', 'watch', 'observe'] },
  { emoji: '👀', keywords: ['eyes', 'look', 'watching', 'see', 'attention', 'stare', 'observe'] },
  { emoji: '👅', keywords: ['tongue', 'taste', 'lick', 'sexy', 'playful'] },
  { emoji: '🦷', keywords: ['tooth', 'dental', 'teeth', 'dentist', 'bite'] },
  { emoji: '🦴', keywords: ['bone', 'skeleton', 'dog', 'strong', 'structure'] },
  // People
  { emoji: '🧑', keywords: ['person', 'human', 'adult', 'user', 'people'] },
  { emoji: '👤', keywords: ['silhouette', 'user', 'person', 'profile', 'account', 'avatar'] },
  { emoji: '👥', keywords: ['people', 'group', 'team', 'users', 'community'] },
  { emoji: '🧑‍💻', keywords: ['developer', 'programmer', 'coder', 'tech', 'computer', 'engineer'] },
  { emoji: '🧑‍🎨', keywords: ['artist', 'painter', 'designer', 'creative', 'art'] },
  { emoji: '🧑‍🏫', keywords: ['teacher', 'instructor', 'educator', 'professor', 'school'] },
  { emoji: '🧑‍⚕️', keywords: ['doctor', 'nurse', 'medical', 'health', 'healthcare'] },
  { emoji: '🧑‍🚀', keywords: ['astronaut', 'space', 'rocket', 'nasa', 'explorer'] },
  { emoji: '💃', keywords: ['dance', 'dancing', 'party', 'salsa', 'woman dancing'] },
  { emoji: '🕺', keywords: ['dance', 'dancing', 'party', 'disco', 'man dancing'] },
  { emoji: '🤸', keywords: ['cartwheel', 'gymnastics', 'flip', 'acrobat', 'flexible'] },
  // Hearts & love
  { emoji: '❤️', keywords: ['heart', 'love', 'red heart', 'like', 'favourite', 'romance'] },
  { emoji: '🧡', keywords: ['orange heart', 'love', 'warm', 'care', 'friendship'] },
  { emoji: '💛', keywords: ['yellow heart', 'love', 'happy', 'friendship', 'sunshine'] },
  { emoji: '💚', keywords: ['green heart', 'nature', 'health', 'growth', 'eco'] },
  { emoji: '💙', keywords: ['blue heart', 'trust', 'calm', 'loyalty', 'cool'] },
  { emoji: '💜', keywords: ['purple heart', 'love', 'compassion', 'luxury', 'creative'] },
  { emoji: '🖤', keywords: ['black heart', 'dark', 'edgy', 'goth', 'cool'] },
  { emoji: '🤍', keywords: ['white heart', 'pure', 'peace', 'snow', 'clean'] },
  { emoji: '🤎', keywords: ['brown heart', 'earth', 'nature', 'warm', 'coffee'] },
  { emoji: '💔', keywords: ['broken heart', 'heartbreak', 'sad', 'loss', 'split'] },
  { emoji: '❣️', keywords: ['heart exclamation', 'love', 'passion', 'strong feeling'] },
  { emoji: '💕', keywords: ['two hearts', 'love', 'affection', 'romance', 'couple'] },
  { emoji: '💞', keywords: ['revolving hearts', 'love', 'spinning', 'romance', 'mutual'] },
  { emoji: '💓', keywords: ['beating heart', 'love', 'pulse', 'alive', 'excited'] },
  { emoji: '💗', keywords: ['growing heart', 'love', 'pink', 'increasing', 'care'] },
  { emoji: '💖', keywords: ['sparkling heart', 'love', 'sparkle', 'amazing', 'star'] },
  { emoji: '💘', keywords: ['heart arrow', 'cupid', 'love', 'struck', 'valentines'] },
  { emoji: '💝', keywords: ['heart ribbon', 'gift', 'love', 'present', 'valentines'] },
  { emoji: '💟', keywords: ['heart decoration', 'love', 'purple', 'care'] },
  // Animals
  { emoji: '🐶', keywords: ['dog', 'puppy', 'pet', 'cute', 'canine', 'woof'] },
  { emoji: '🐱', keywords: ['cat', 'kitten', 'pet', 'cute', 'feline', 'meow'] },
  { emoji: '🐭', keywords: ['mouse', 'rat', 'rodent', 'small', 'cute'] },
  { emoji: '🐹', keywords: ['hamster', 'cute', 'pet', 'rodent', 'small'] },
  { emoji: '🐰', keywords: ['rabbit', 'bunny', 'easter', 'cute', 'hop', 'fast'] },
  { emoji: '🦊', keywords: ['fox', 'clever', 'sly', 'orange', 'wild'] },
  { emoji: '🐻', keywords: ['bear', 'cute', 'brown', 'teddy', 'animal'] },
  { emoji: '🐼', keywords: ['panda', 'china', 'cute', 'black white', 'bear'] },
  { emoji: '🐻‍❄️', keywords: ['polar bear', 'arctic', 'white', 'cold', 'ice'] },
  { emoji: '🐨', keywords: ['koala', 'australia', 'cute', 'bear', 'marsupial'] },
  { emoji: '🐯', keywords: ['tiger', 'wild', 'fierce', 'stripes', 'cat'] },
  { emoji: '🦁', keywords: ['lion', 'king', 'pride', 'fierce', 'mane', 'roar'] },
  { emoji: '🐮', keywords: ['cow', 'milk', 'moo', 'farm', 'animal', 'bovine'] },
  { emoji: '🐷', keywords: ['pig', 'oink', 'farm', 'pink', 'animal', 'pork'] },
  { emoji: '🐸', keywords: ['frog', 'green', 'jump', 'pond', 'ribbit'] },
  { emoji: '🐵', keywords: ['monkey', 'ape', 'animal', 'funny', 'tree'] },
  { emoji: '🙈', keywords: ['see no evil', 'monkey', 'hide', 'shy', 'embarrassed'] },
  { emoji: '🙉', keywords: ['hear no evil', 'monkey', 'deaf', 'ignore', 'ears'] },
  { emoji: '🙊', keywords: ['speak no evil', 'monkey', 'quiet', 'silent', 'mouth'] },
  { emoji: '🐔', keywords: ['chicken', 'bird', 'farm', 'cluck', 'hen'] },
  { emoji: '🐧', keywords: ['penguin', 'cold', 'arctic', 'cute', 'bird', 'waddle'] },
  { emoji: '🐦', keywords: ['bird', 'fly', 'twitter', 'tweet', 'feather'] },
  { emoji: '🐤', keywords: ['chick', 'baby bird', 'yellow', 'cute', 'hatching'] },
  { emoji: '🦆', keywords: ['duck', 'quack', 'pond', 'bird', 'water'] },
  { emoji: '🦅', keywords: ['eagle', 'bird', 'fly', 'majestic', 'freedom', 'usa'] },
  { emoji: '🦉', keywords: ['owl', 'wise', 'night', 'bird', 'wisdom', 'hoot'] },
  { emoji: '🦇', keywords: ['bat', 'halloween', 'night', 'fly', 'dark', 'vampire'] },
  { emoji: '🐺', keywords: ['wolf', 'howl', 'wild', 'pack', 'animal'] },
  { emoji: '🐗', keywords: ['boar', 'pig', 'wild', 'tusk', 'animal'] },
  { emoji: '🐴', keywords: ['horse', 'pony', 'ride', 'neigh', 'fast'] },
  { emoji: '🦄', keywords: ['unicorn', 'magical', 'rainbow', 'fantasy', 'horse'] },
  { emoji: '🐝', keywords: ['bee', 'honey', 'sting', 'yellow', 'insect', 'buzz'] },
  { emoji: '🐛', keywords: ['bug', 'caterpillar', 'insect', 'error', 'issue', 'worm'] },
  { emoji: '🦋', keywords: ['butterfly', 'pretty', 'transform', 'fly', 'colorful'] },
  { emoji: '🐌', keywords: ['snail', 'slow', 'shell', 'garden', 'slug'] },
  { emoji: '🐞', keywords: ['ladybug', 'ladybird', 'luck', 'red', 'insect', 'spots'] },
  { emoji: '🐜', keywords: ['ant', 'insect', 'tiny', 'worker', 'colony'] },
  { emoji: '🦟', keywords: ['mosquito', 'bug', 'bite', 'insect', 'malaria'] },
  { emoji: '🕷️', keywords: ['spider', 'web', 'creepy', 'halloween', 'arachnid', 'scary'] },
  { emoji: '🦂', keywords: ['scorpion', 'zodiac', 'sting', 'desert', 'dangerous'] },
  { emoji: '🐢', keywords: ['turtle', 'slow', 'shell', 'sea', 'reptile', 'tortoise'] },
  { emoji: '🐍', keywords: ['snake', 'reptile', 'coil', 'venom', 'slither'] },
  { emoji: '🦎', keywords: ['lizard', 'reptile', 'green', 'gecko', 'scales'] },
  { emoji: '🦖', keywords: ['dinosaur', 't-rex', 'prehistoric', 'extinct', 'jurassic'] },
  { emoji: '🦕', keywords: ['dinosaur', 'sauropod', 'prehistoric', 'long neck', 'brachiosaurus'] },
  { emoji: '🐙', keywords: ['octopus', 'tentacles', 'sea', 'ocean', 'arms'] },
  { emoji: '🦑', keywords: ['squid', 'tentacles', 'ocean', 'ink', 'sea'] },
  { emoji: '🦐', keywords: ['shrimp', 'seafood', 'prawn', 'tiny', 'ocean'] },
  { emoji: '🦞', keywords: ['lobster', 'seafood', 'red', 'ocean', 'claws'] },
  { emoji: '🦀', keywords: ['crab', 'seafood', 'red', 'sideways', 'claws', 'pinch'] },
  { emoji: '🐡', keywords: ['blowfish', 'puffer', 'fish', 'spiky', 'ocean'] },
  { emoji: '🐠', keywords: ['tropical fish', 'colorful', 'ocean', 'nemo', 'aquarium'] },
  { emoji: '🐟', keywords: ['fish', 'ocean', 'sea', 'swim', 'aquatic'] },
  { emoji: '🐬', keywords: ['dolphin', 'ocean', 'smart', 'flipper', 'sea mammal'] },
  { emoji: '🦭', keywords: ['seal', 'ocean', 'arctic', 'cute', 'flipper', 'clap'] },
  { emoji: '🐳', keywords: ['whale', 'ocean', 'big', 'blue', 'spout'] },
  { emoji: '🐋', keywords: ['whale', 'ocean', 'sperm whale', 'big', 'sea'] },
  { emoji: '🦈', keywords: ['shark', 'teeth', 'ocean', 'scary', 'predator', 'jaw'] },
  { emoji: '🐊', keywords: ['crocodile', 'alligator', 'teeth', 'reptile', 'dangerous', 'green'] },
  { emoji: '🐅', keywords: ['tiger', 'stripes', 'wild', 'fierce', 'big cat'] },
  { emoji: '🐆', keywords: ['leopard', 'spots', 'cheetah', 'fast', 'wild'] },
  { emoji: '🦓', keywords: ['zebra', 'stripes', 'africa', 'horse', 'black white'] },
  { emoji: '🦍', keywords: ['gorilla', 'ape', 'strong', 'primate', 'kong'] },
  { emoji: '🦧', keywords: ['orangutan', 'ape', 'primate', 'forest', 'climbing'] },
  { emoji: '🦣', keywords: ['mammoth', 'extinct', 'prehistoric', 'tusks', 'woolly'] },
  { emoji: '🐘', keywords: ['elephant', 'big', 'memory', 'trunk', 'africa', 'large'] },
  { emoji: '🦛', keywords: ['hippo', 'hippopotamus', 'water', 'africa', 'big', 'heavy'] },
  { emoji: '🦏', keywords: ['rhinoceros', 'rhino', 'horn', 'africa', 'heavy'] },
  { emoji: '🐪', keywords: ['camel', 'hump', 'desert', 'dry', 'sand'] },
  { emoji: '🐫', keywords: ['two hump camel', 'bactrian', 'desert', 'sand', 'travel'] },
  { emoji: '🦒', keywords: ['giraffe', 'long neck', 'tall', 'africa', 'spots'] },
  { emoji: '🦘', keywords: ['kangaroo', 'australia', 'jump', 'pouch', 'marsupial'] },
  { emoji: '🦬', keywords: ['bison', 'buffalo', 'heavy', 'horns', 'plains'] },
  { emoji: '🐃', keywords: ['water buffalo', 'ox', 'farm', 'horns', 'heavy'] },
  { emoji: '🐂', keywords: ['ox', 'bull', 'strong', 'farm', 'zodiac'] },
  { emoji: '🐄', keywords: ['cow', 'milk', 'farm', 'moo', 'bovine'] },
  { emoji: '🐎', keywords: ['horse', 'racing', 'gallop', 'fast', 'equestrian'] },
  { emoji: '🐖', keywords: ['pig', 'farm', 'oink', 'bacon', 'pork'] },
  { emoji: '🐏', keywords: ['ram', 'sheep', 'wool', 'horns', 'male'] },
  { emoji: '🐑', keywords: ['sheep', 'wool', 'fluffy', 'white', 'baa', 'farm'] },
  { emoji: '🦙', keywords: ['llama', 'alpaca', 'fluffy', 'south america', 'wool'] },
  { emoji: '🐐', keywords: ['goat', 'horns', 'mountain', 'farm', 'beard'] },
  { emoji: '🦌', keywords: ['deer', 'antlers', 'reindeer', 'forest', 'rudolf'] },
  { emoji: '🐕', keywords: ['dog', 'pet', 'puppy', 'canine', 'woof', 'bark'] },
  { emoji: '🐩', keywords: ['poodle', 'dog', 'fancy', 'fluffy', 'pet'] },
  { emoji: '🦮', keywords: ['guide dog', 'blind', 'service dog', 'golden retriever', 'assist'] },
  { emoji: '🐈', keywords: ['cat', 'pet', 'feline', 'meow', 'purr'] },
  { emoji: '🐓', keywords: ['rooster', 'chicken', 'cock', 'morning', 'farm', 'crow'] },
  { emoji: '🦃', keywords: ['turkey', 'thanksgiving', 'bird', 'farm', 'gobble'] },
  { emoji: '🦤', keywords: ['dodo', 'extinct', 'bird', 'island', 'flightless'] },
  { emoji: '🦚', keywords: ['peacock', 'colorful', 'feathers', 'proud', 'beautiful'] },
  { emoji: '🦜', keywords: ['parrot', 'bird', 'colorful', 'talk', 'mimic', 'pirate'] },
  { emoji: '🦢', keywords: ['swan', 'elegant', 'white', 'graceful', 'bird', 'lake'] },
  { emoji: '🦩', keywords: ['flamingo', 'pink', 'legs', 'tropical', 'bird'] },
  { emoji: '🕊️', keywords: ['dove', 'peace', 'white bird', 'gentle', 'love'] },
  { emoji: '🐇', keywords: ['rabbit', 'bunny', 'hop', 'white', 'pet'] },
  { emoji: '🦝', keywords: ['raccoon', 'mask', 'trash panda', 'night', 'clever'] },
  { emoji: '🦨', keywords: ['skunk', 'smell', 'stink', 'black white', 'spray'] },
  { emoji: '🦡', keywords: ['badger', 'forest', 'nocturnal', 'stripe', 'dig'] },
  { emoji: '🦦', keywords: ['otter', 'cute', 'swim', 'river', 'hold hands'] },
  { emoji: '🦥', keywords: ['sloth', 'slow', 'hang', 'lazy', 'tree'] },
  { emoji: '🐁', keywords: ['mouse', 'rodent', 'small', 'cute', 'cheese'] },
  { emoji: '🐀', keywords: ['rat', 'rodent', 'sewer', 'pests', 'small'] },
  { emoji: '🐿️', keywords: ['chipmunk', 'squirrel', 'nuts', 'cute', 'striped'] },
  { emoji: '🦔', keywords: ['hedgehog', 'spiky', 'cute', 'small', 'prickly'] },
  // Nature & plants
  { emoji: '🌵', keywords: ['cactus', 'desert', 'dry', 'plant', 'prickly', 'spiky'] },
  { emoji: '🎄', keywords: ['christmas tree', 'holiday', 'festive', 'xmas', 'decoration'] },
  { emoji: '🌲', keywords: ['evergreen', 'tree', 'forest', 'pine', 'nature'] },
  { emoji: '🌳', keywords: ['tree', 'deciduous', 'nature', 'park', 'leaves', 'forest'] },
  { emoji: '🌴', keywords: ['palm tree', 'tropical', 'beach', 'coconut', 'holiday'] },
  { emoji: '🌱', keywords: ['seedling', 'grow', 'new', 'plant', 'start', 'sprout', 'nature'] },
  { emoji: '🌿', keywords: ['herb', 'green', 'nature', 'plant', 'fresh', 'leaf', 'organic'] },
  { emoji: '☘️', keywords: ['shamrock', 'clover', 'ireland', 'irish', 'luck', 'green'] },
  { emoji: '🍀', keywords: ['four leaf clover', 'luck', 'lucky', 'fortune', 'green'] },
  { emoji: '🎋', keywords: ['bamboo', 'tanabata', 'japanese', 'green', 'plant'] },
  { emoji: '🎍', keywords: ['pine decoration', 'japanese', 'new year', 'bamboo', 'celebration'] },
  { emoji: '🍃', keywords: ['leaves', 'flutter', 'green', 'nature', 'wind', 'fall'] },
  { emoji: '🍂', keywords: ['fallen leaf', 'autumn', 'fall', 'orange', 'nature'] },
  { emoji: '🍁', keywords: ['maple leaf', 'canada', 'autumn', 'fall', 'red', 'orange'] },
  { emoji: '🍄', keywords: ['mushroom', 'fungi', 'forest', 'mario', 'grow', 'red'] },
  { emoji: '🌾', keywords: ['wheat', 'grain', 'harvest', 'farm', 'cereal', 'sheaf'] },
  { emoji: '💐', keywords: ['bouquet', 'flowers', 'gift', 'floral', 'pretty', 'bunch'] },
  { emoji: '🌷', keywords: ['tulip', 'flower', 'spring', 'pink', 'beautiful'] },
  { emoji: '🌹', keywords: ['rose', 'flower', 'love', 'red', 'romantic', 'valentines'] },
  { emoji: '🥀', keywords: ['wilted rose', 'dead flower', 'sad', 'end', 'decay'] },
  { emoji: '🌺', keywords: ['hibiscus', 'flower', 'tropical', 'pink', 'hawaii'] },
  { emoji: '🌸', keywords: ['cherry blossom', 'sakura', 'japan', 'spring', 'pink', 'flower'] },
  { emoji: '🌼', keywords: ['blossom', 'flower', 'yellow', 'daisy', 'spring', 'bloom'] },
  { emoji: '🌻', keywords: ['sunflower', 'sun', 'yellow', 'bright', 'summer', 'flower'] },
  { emoji: '🪨', keywords: ['rock', 'stone', 'hard', 'heavy', 'mineral', 'boulder'] },
  { emoji: '🌊', keywords: ['wave', 'ocean', 'sea', 'surf', 'water', 'tsunami'] },
  { emoji: '💧', keywords: ['droplet', 'water', 'wet', 'rain', 'tear', 'blue'] },
  { emoji: '💦', keywords: ['sweat drops', 'water', 'splashing', 'wet', 'rain'] },
  { emoji: '🌈', keywords: ['rainbow', 'colorful', 'after rain', 'pride', 'hope', 'lgbtq'] },
  { emoji: '☀️', keywords: ['sun', 'sunny', 'warm', 'bright', 'day', 'summer', 'light'] },
  { emoji: '🌤️', keywords: ['sun cloud', 'mostly sunny', 'partly cloudy', 'weather'] },
  { emoji: '⛅', keywords: ['partly cloudy', 'sun cloud', 'weather', 'mixed'] },
  { emoji: '🌦️', keywords: ['rain sun', 'showers', 'weather', 'mixed'] },
  { emoji: '🌧️', keywords: ['rain cloud', 'rainy', 'shower', 'weather', 'wet'] },
  { emoji: '⛈️', keywords: ['storm', 'thunder', 'lightning', 'rain', 'weather'] },
  { emoji: '🌩️', keywords: ['lightning', 'thunder', 'electric', 'bolt', 'storm'] },
  { emoji: '🌨️', keywords: ['snow cloud', 'snowing', 'blizzard', 'winter', 'cold'] },
  { emoji: '❄️', keywords: ['snowflake', 'cold', 'winter', 'ice', 'snow', 'frozen', 'crystal'] },
  { emoji: '⛄', keywords: ['snowman', 'winter', 'snow', 'cold', 'holiday'] },
  { emoji: '🌬️', keywords: ['wind', 'blow', 'breeze', 'air', 'gust'] },
  { emoji: '💨', keywords: ['wind', 'fast', 'dash', 'blow', 'gust', 'air', 'speed'] },
  { emoji: '🌀', keywords: ['cyclone', 'tornado', 'spin', 'swirl', 'typhoon', 'spiral'] },
  { emoji: '🌙', keywords: ['moon', 'night', 'crescent', 'dark', 'sleep'] },
  { emoji: '⭐', keywords: ['star', 'favourite', 'great', 'gold', 'rating', 'shiny'] },
  { emoji: '🌟', keywords: ['glowing star', 'amazing', 'shine', 'bright', 'celebrity'] },
  { emoji: '✨', keywords: ['sparkles', 'shine', 'magic', 'glitter', 'stars', 'wow'] },
  { emoji: '⚡', keywords: ['lightning', 'electric', 'fast', 'bolt', 'energy', 'power', 'thunder'] },
  { emoji: '🔥', keywords: ['fire', 'hot', 'flame', 'lit', 'burn', 'trending', 'spicy', 'ablaze'] },
  { emoji: '🌍', keywords: ['earth', 'world', 'globe', 'planet', 'africa', 'europe', 'international'] },
  { emoji: '🌎', keywords: ['earth', 'world', 'globe', 'americas', 'planet', 'international'] },
  { emoji: '🌏', keywords: ['earth', 'world', 'globe', 'asia', 'planet', 'international'] },
  { emoji: '🌐', keywords: ['globe', 'internet', 'world', 'web', 'international', 'network'] },
  { emoji: '🗺️', keywords: ['map', 'world', 'geography', 'travel', 'explore'] },
  // Food & drink
  { emoji: '🍎', keywords: ['apple', 'red', 'fruit', 'healthy', 'food'] },
  { emoji: '🍊', keywords: ['orange', 'citrus', 'fruit', 'tangerine', 'juicy'] },
  { emoji: '🍋', keywords: ['lemon', 'citrus', 'sour', 'yellow', 'fruit', 'zest'] },
  { emoji: '🍇', keywords: ['grapes', 'fruit', 'purple', 'wine', 'vine'] },
  { emoji: '🍓', keywords: ['strawberry', 'fruit', 'red', 'sweet', 'berry'] },
  { emoji: '🍑', keywords: ['peach', 'fruit', 'butt', 'booty', 'juicy'] },
  { emoji: '🍒', keywords: ['cherries', 'fruit', 'red', 'sweet', 'pair'] },
  { emoji: '🍍', keywords: ['pineapple', 'tropical', 'fruit', 'hawaii', 'sweet'] },
  { emoji: '🥭', keywords: ['mango', 'tropical', 'fruit', 'sweet', 'orange'] },
  { emoji: '🥑', keywords: ['avocado', 'healthy', 'green', 'toast', 'guac'] },
  { emoji: '🍆', keywords: ['eggplant', 'aubergine', 'purple', 'vegetable', 'phallic'] },
  { emoji: '🥦', keywords: ['broccoli', 'green', 'vegetable', 'healthy', 'trees'] },
  { emoji: '🥕', keywords: ['carrot', 'orange', 'vegetable', 'healthy', 'bunny'] },
  { emoji: '🌽', keywords: ['corn', 'maize', 'yellow', 'vegetable', 'popcorn', 'cob'] },
  { emoji: '🌶️', keywords: ['hot pepper', 'spicy', 'chili', 'red', 'hot', 'fiery'] },
  { emoji: '🍕', keywords: ['pizza', 'italian', 'food', 'cheese', 'slice', 'delicious'] },
  { emoji: '🍔', keywords: ['burger', 'hamburger', 'food', 'fast food', 'beef', 'sandwich'] },
  { emoji: '🍟', keywords: ['fries', 'chips', 'fast food', 'potato', 'salt', 'mcdonalds'] },
  { emoji: '🌮', keywords: ['taco', 'mexican', 'food', 'tortilla', 'spicy'] },
  { emoji: '🌯', keywords: ['burrito', 'wrap', 'mexican', 'food', 'tortilla'] },
  { emoji: '🍜', keywords: ['noodles', 'ramen', 'noodle soup', 'asian', 'food'] },
  { emoji: '🍝', keywords: ['spaghetti', 'pasta', 'italian', 'food', 'noodles'] },
  { emoji: '🍣', keywords: ['sushi', 'japanese', 'fish', 'rice', 'food', 'raw'] },
  { emoji: '🍱', keywords: ['bento', 'box', 'japanese', 'food', 'lunch'] },
  { emoji: '🍦', keywords: ['ice cream', 'soft serve', 'sweets', 'cold', 'dessert'] },
  { emoji: '🍰', keywords: ['cake', 'slice', 'birthday', 'dessert', 'sweet', 'party'] },
  { emoji: '🎂', keywords: ['birthday cake', 'celebration', 'candles', 'party', 'bake'] },
  { emoji: '🍩', keywords: ['donut', 'doughnut', 'sweet', 'round', 'sprinkles', 'dessert'] },
  { emoji: '🍪', keywords: ['cookie', 'biscuit', 'bake', 'sweet', 'chocolate chip', 'snack'] },
  { emoji: '🍫', keywords: ['chocolate', 'bar', 'sweet', 'cocoa', 'candy'] },
  { emoji: '🍬', keywords: ['candy', 'sweets', 'sugar', 'lollipop', 'treat'] },
  { emoji: '🍭', keywords: ['lollipop', 'candy', 'sweets', 'sugar', 'colourful'] },
  { emoji: '☕', keywords: ['coffee', 'hot drink', 'cafe', 'morning', 'caffeine', 'mug'] },
  { emoji: '🍵', keywords: ['tea', 'green tea', 'hot drink', 'calm', 'cup', 'herbal'] },
  { emoji: '🧋', keywords: ['bubble tea', 'boba', 'drink', 'tapioca', 'milk tea', 'taiwanese'] },
  { emoji: '🥤', keywords: ['drink', 'cup', 'soda', 'cold drink', 'straw', 'fast food'] },
  { emoji: '🍺', keywords: ['beer', 'pint', 'drink', 'alcohol', 'cheers', 'pub', 'lager'] },
  { emoji: '🍻', keywords: ['beers', 'cheers', 'toast', 'clink', 'drink', 'celebration'] },
  { emoji: '🥂', keywords: ['champagne glasses', 'toast', 'celebrate', 'cheers', 'clink', 'party'] },
  { emoji: '🍷', keywords: ['wine', 'drink', 'red wine', 'alcohol', 'glass', 'elegant'] },
  { emoji: '🥃', keywords: ['whiskey', 'tumbler', 'bourbon', 'alcohol', 'drink', 'spirits'] },
  { emoji: '🧃', keywords: ['juice box', 'drink', 'kids', 'juice', 'straw', 'fruit'] },
  { emoji: '🥛', keywords: ['milk', 'glass', 'white', 'drink', 'dairy', 'healthy'] },
  { emoji: '🍼', keywords: ['baby bottle', 'milk', 'infant', 'feed', 'baby'] },
  // Activities & sports
  { emoji: '⚽', keywords: ['soccer', 'football', 'sport', 'ball', 'kick', 'goal'] },
  { emoji: '🏀', keywords: ['basketball', 'sport', 'ball', 'hoop', 'nba', 'dunk'] },
  { emoji: '🏈', keywords: ['american football', 'sport', 'nfl', 'ball', 'touchdown'] },
  { emoji: '⚾', keywords: ['baseball', 'sport', 'ball', 'pitch', 'mlb', 'hit'] },
  { emoji: '🎾', keywords: ['tennis', 'sport', 'ball', 'racket', 'serve', 'wimbledon'] },
  { emoji: '🏐', keywords: ['volleyball', 'sport', 'ball', 'serve', 'spike', 'beach'] },
  { emoji: '🏉', keywords: ['rugby', 'sport', 'ball', 'tackle', 'scrum'] },
  { emoji: '🎱', keywords: ['pool', 'billiards', 'eight ball', 'snooker', 'game'] },
  { emoji: '🏓', keywords: ['ping pong', 'table tennis', 'sport', 'paddle', 'ball'] },
  { emoji: '🎯', keywords: ['target', 'bullseye', 'aim', 'goal', 'dart', 'accurate', 'precision'] },
  { emoji: '🎮', keywords: ['video game', 'gaming', 'controller', 'play', 'gamer', 'console'] },
  { emoji: '🕹️', keywords: ['joystick', 'game', 'control', 'retro', 'arcade', 'gaming'] },
  { emoji: '🎲', keywords: ['dice', 'game', 'random', 'luck', 'chance', 'board game', 'roll'] },
  { emoji: '🎭', keywords: ['theatre', 'theater', 'performing arts', 'mask', 'drama', 'show'] },
  { emoji: '🎨', keywords: ['art', 'palette', 'paint', 'creative', 'design', 'color', 'artist'] },
  { emoji: '🎬', keywords: ['movie', 'film', 'cinema', 'action', 'clapper', 'director'] },
  { emoji: '🎤', keywords: ['microphone', 'sing', 'music', 'karaoke', 'voice', 'performance'] },
  { emoji: '🎧', keywords: ['headphones', 'music', 'listen', 'audio', 'sound', 'earphones'] },
  { emoji: '🎵', keywords: ['music note', 'music', 'song', 'tune', 'melody', 'sound'] },
  { emoji: '🎶', keywords: ['music notes', 'music', 'song', 'melody', 'tune', 'notes'] },
  { emoji: '🎸', keywords: ['guitar', 'music', 'rock', 'string', 'band', 'instrument'] },
  { emoji: '🎹', keywords: ['piano', 'keyboard', 'music', 'keys', 'instrument', 'classical'] },
  { emoji: '🥁', keywords: ['drum', 'music', 'beat', 'rhythm', 'percussion', 'band'] },
  { emoji: '🎺', keywords: ['trumpet', 'music', 'brass', 'instrument', 'jazz', 'fanfare'] },
  { emoji: '🎻', keywords: ['violin', 'music', 'string', 'classical', 'orchestra', 'fiddle'] },
  { emoji: '🏆', keywords: ['trophy', 'win', 'champion', 'award', 'first place', 'victory', 'gold'] },
  { emoji: '🥇', keywords: ['gold medal', 'first', 'winner', 'champion', 'best', 'top'] },
  { emoji: '🥈', keywords: ['silver medal', 'second', 'runner up', 'almost'] },
  { emoji: '🥉', keywords: ['bronze medal', 'third', 'third place'] },
  { emoji: '🏅', keywords: ['sports medal', 'award', 'winner', 'achievement'] },
  { emoji: '🎖️', keywords: ['military medal', 'award', 'honor', 'decoration', 'achievement'] },
  { emoji: '🎗️', keywords: ['ribbon', 'awareness', 'reminder', 'badge'] },
  { emoji: '🎟️', keywords: ['ticket', 'event', 'admission', 'concert', 'show'] },
  { emoji: '🎫', keywords: ['ticket', 'entrance', 'pass', 'concert', 'movie'] },
  { emoji: '🎪', keywords: ['circus', 'tent', 'show', 'performance', 'carnival'] },
  // Travel & places
  { emoji: '🚗', keywords: ['car', 'drive', 'vehicle', 'auto', 'road trip', 'sedan'] },
  { emoji: '🚕', keywords: ['taxi', 'cab', 'yellow car', 'ride', 'hire'] },
  { emoji: '🚙', keywords: ['suv', 'car', 'vehicle', 'drive', 'crossover'] },
  { emoji: '🚌', keywords: ['bus', 'transit', 'transport', 'commute', 'public'] },
  { emoji: '🚎', keywords: ['trolleybus', 'tram', 'bus', 'transit'] },
  { emoji: '🏎️', keywords: ['racing car', 'formula 1', 'fast', 'speed', 'sport'] },
  { emoji: '🚓', keywords: ['police car', 'cop', 'law', 'patrol', 'blue lights'] },
  { emoji: '🚑', keywords: ['ambulance', 'medical', 'emergency', 'hospital', 'rescue'] },
  { emoji: '🚒', keywords: ['fire truck', 'firefighter', 'rescue', 'red', 'emergency'] },
  { emoji: '🚐', keywords: ['minibus', 'van', 'vehicle', 'transport', 'shuttle'] },
  { emoji: '🚚', keywords: ['truck', 'delivery', 'transport', 'lorry', 'freight'] },
  { emoji: '🚛', keywords: ['articulated truck', 'semi', 'freight', 'lorry', 'big rig'] },
  { emoji: '🚜', keywords: ['tractor', 'farm', 'agriculture', 'field', 'heavy'] },
  { emoji: '🛺', keywords: ['auto rickshaw', 'tuk tuk', 'asia', 'taxi', 'three wheel'] },
  { emoji: '🚲', keywords: ['bicycle', 'bike', 'cycle', 'eco', 'exercise', 'pedal'] },
  { emoji: '🛴', keywords: ['scooter', 'kick scooter', 'ride', 'micro', 'transport'] },
  { emoji: '🛵', keywords: ['scooter', 'moped', 'motor scooter', 'ride', 'two wheels'] },
  { emoji: '🏍️', keywords: ['motorcycle', 'motorbike', 'fast', 'ride', 'biker'] },
  { emoji: '✈️', keywords: ['airplane', 'plane', 'fly', 'travel', 'flight', 'air', 'transport'] },
  { emoji: '🚀', keywords: ['rocket', 'launch', 'fast', 'ship', 'space', 'blast off'] },
  { emoji: '🛸', keywords: ['ufo', 'alien', 'flying saucer', 'space', 'extraterrestrial'] },
  { emoji: '🚁', keywords: ['helicopter', 'fly', 'rotor', 'air', 'transport'] },
  { emoji: '⛵', keywords: ['sailboat', 'sail', 'sea', 'wind', 'boat'] },
  { emoji: '🚢', keywords: ['ship', 'cruise', 'boat', 'ocean', 'travel', 'sailing'] },
  { emoji: '⛽', keywords: ['fuel', 'gas', 'petrol', 'station', 'energy'] },
  { emoji: '🚦', keywords: ['traffic light', 'green', 'go', 'stop', 'red'] },
  { emoji: '🗼', keywords: ['tokyo tower', 'japan', 'landmark', 'red', 'tall'] },
  { emoji: '🗽', keywords: ['statue of liberty', 'new york', 'usa', 'freedom', 'landmark'] },
  { emoji: '🗿', keywords: ['moai', 'easter island', 'stone', 'monument', 'grey'] },
  { emoji: '🏠', keywords: ['house', 'home', 'building', 'live', 'domestic'] },
  { emoji: '🏡', keywords: ['house garden', 'home', 'yard', 'suburban', 'building'] },
  { emoji: '🏢', keywords: ['office', 'building', 'work', 'corporate', 'skyscraper'] },
  { emoji: '🏣', keywords: ['post office', 'mail', 'japan', 'building'] },
  { emoji: '🏥', keywords: ['hospital', 'medical', 'health', 'clinic', 'emergency'] },
  { emoji: '🏦', keywords: ['bank', 'money', 'finance', 'building', 'savings'] },
  { emoji: '🏨', keywords: ['hotel', 'travel', 'stay', 'room', 'accommodation'] },
  { emoji: '🏩', keywords: ['love hotel', 'heart', 'romantic', 'japan'] },
  { emoji: '🏪', keywords: ['convenience store', 'shop', 'retail', 'market', 'night'] },
  { emoji: '🏫', keywords: ['school', 'education', 'learn', 'building', 'study'] },
  { emoji: '🏬', keywords: ['department store', 'shopping', 'retail', 'building', 'mall'] },
  { emoji: '🏭', keywords: ['factory', 'industrial', 'manufacture', 'building', 'production'] },
  { emoji: '🗻', keywords: ['mount fuji', 'mountain', 'japan', 'snow', 'peak'] },
  { emoji: '⛰️', keywords: ['mountain', 'peak', 'hike', 'climb', 'nature', 'high'] },
  { emoji: '🌋', keywords: ['volcano', 'eruption', 'lava', 'mountain', 'natural disaster'] },
  { emoji: '🏝️', keywords: ['island', 'desert island', 'beach', 'tropical', 'paradise'] },
  { emoji: '🏖️', keywords: ['beach', 'sun', 'sand', 'holiday', 'ocean', 'summer', 'relax'] },
  { emoji: '🌅', keywords: ['sunrise', 'dawn', 'morning', 'orange', 'sky', 'horizon'] },
  { emoji: '🌄', keywords: ['sunrise mountains', 'dawn', 'morning', 'nature', 'view'] },
  { emoji: '🌃', keywords: ['night city', 'stars', 'dark', 'urban', 'evening'] },
  { emoji: '🌆', keywords: ['cityscape', 'urban', 'evening', 'city', 'skyline'] },
  { emoji: '🌇', keywords: ['sunset city', 'evening', 'dusk', 'orange', 'skyline'] },
  { emoji: '🌉', keywords: ['bridge night', 'city', 'water', 'lights', 'crossing'] },
  // Objects & tech
  { emoji: '📱', keywords: ['phone', 'mobile', 'cell', 'smartphone', 'call', 'iphone', 'device'] },
  { emoji: '💻', keywords: ['laptop', 'computer', 'mac', 'work', 'coding', 'tech', 'screen'] },
  { emoji: '🖥️', keywords: ['desktop', 'computer', 'monitor', 'screen', 'pc', 'tech'] },
  { emoji: '🖨️', keywords: ['printer', 'print', 'office', 'paper', 'document'] },
  { emoji: '⌨️', keywords: ['keyboard', 'type', 'computer', 'keys', 'input', 'typing'] },
  { emoji: '🖱️', keywords: ['mouse', 'computer', 'click', 'cursor', 'pointer'] },
  { emoji: '📷', keywords: ['camera', 'photo', 'picture', 'photography', 'snap', 'shot'] },
  { emoji: '📸', keywords: ['camera flash', 'photo', 'selfie', 'snap', 'picture'] },
  { emoji: '📹', keywords: ['video camera', 'record', 'film', 'movie', 'camera'] },
  { emoji: '📺', keywords: ['television', 'tv', 'watch', 'screen', 'broadcast', 'show'] },
  { emoji: '📻', keywords: ['radio', 'audio', 'music', 'broadcast', 'old', 'frequency'] },
  { emoji: '📡', keywords: ['satellite', 'antenna', 'signal', 'broadcast', 'receive'] },
  { emoji: '🔋', keywords: ['battery', 'power', 'energy', 'charge', 'full', 'dead'] },
  { emoji: '🔌', keywords: ['plug', 'power', 'electric', 'charge', 'socket', 'outlet'] },
  { emoji: '💡', keywords: ['light bulb', 'idea', 'bright', 'tip', 'insight', 'illuminate'] },
  { emoji: '🔦', keywords: ['flashlight', 'torch', 'light', 'dark', 'illuminate'] },
  { emoji: '🕯️', keywords: ['candle', 'flame', 'light', 'romance', 'birthday', 'dark'] },
  { emoji: '🗑️', keywords: ['trash', 'bin', 'garbage', 'delete', 'remove', 'waste'] },
  { emoji: '🔧', keywords: ['wrench', 'tool', 'fix', 'repair', 'mechanic', 'settings'] },
  { emoji: '🔨', keywords: ['hammer', 'tool', 'build', 'hit', 'construct', 'bang'] },
  { emoji: '⚒️', keywords: ['hammer pick', 'tool', 'mining', 'work', 'build'] },
  { emoji: '🛠️', keywords: ['tools', 'hammer wrench', 'fix', 'repair', 'build', 'maintenance'] },
  { emoji: '⛏️', keywords: ['pick', 'mining', 'tool', 'dig', 'hack', 'mine'] },
  { emoji: '🔩', keywords: ['nut bolt', 'screw', 'fastener', 'hardware', 'metal', 'fix'] },
  { emoji: '🗜️', keywords: ['clamp', 'tool', 'compress', 'squeeze', 'vice'] },
  { emoji: '🔑', keywords: ['key', 'lock', 'unlock', 'access', 'password', 'security'] },
  { emoji: '🗝️', keywords: ['old key', 'antique', 'unlock', 'lock', 'access', 'classic'] },
  { emoji: '🔐', keywords: ['locked key', 'secure', 'locked', 'private', 'protect'] },
  { emoji: '🔒', keywords: ['locked', 'lock', 'secure', 'private', 'closed', 'security'] },
  { emoji: '🔓', keywords: ['unlocked', 'open', 'access', 'unsecure', 'lock'] },
  { emoji: '🔏', keywords: ['locked pen', 'sign', 'private', 'document', 'seal'] },
  { emoji: '🔗', keywords: ['link', 'chain', 'connect', 'url', 'attachment', 'linked'] },
  { emoji: '📎', keywords: ['paperclip', 'attach', 'clip', 'link', 'fasten', 'attachment'] },
  { emoji: '📌', keywords: ['pin', 'pinned', 'mark', 'important', 'location', 'bookmark'] },
  { emoji: '📍', keywords: ['pin location', 'map', 'place', 'location', 'here', 'point'] },
  { emoji: '✂️', keywords: ['scissors', 'cut', 'trim', 'clip', 'snip', 'craft'] },
  { emoji: '🗃️', keywords: ['card file box', 'archive', 'organise', 'storage', 'file'] },
  { emoji: '🗄️', keywords: ['filing cabinet', 'storage', 'archive', 'office', 'data'] },
  { emoji: '🗂️', keywords: ['file divider', 'tabs', 'organise', 'folder', 'sort'] },
  { emoji: '📁', keywords: ['folder', 'directory', 'file', 'organise', 'storage'] },
  { emoji: '📂', keywords: ['open folder', 'directory', 'file', 'access', 'storage'] },
  { emoji: '📋', keywords: ['clipboard', 'notes', 'list', 'paste', 'document'] },
  { emoji: '📊', keywords: ['chart', 'graph', 'data', 'analytics', 'bar chart', 'statistics', 'metrics'] },
  { emoji: '📈', keywords: ['chart up', 'growth', 'increase', 'trend', 'rising', 'profit', 'stock'] },
  { emoji: '📉', keywords: ['chart down', 'decline', 'decrease', 'trend', 'loss', 'falling'] },
  { emoji: '📄', keywords: ['document', 'file', 'page', 'paper', 'text', 'note'] },
  { emoji: '📃', keywords: ['page', 'document', 'curl', 'paper', 'text'] },
  { emoji: '📑', keywords: ['bookmark tabs', 'document', 'pages', 'multi', 'tabbed'] },
  { emoji: '📝', keywords: ['memo', 'note', 'write', 'pencil', 'document', 'edit', 'list', 'notes'] },
  { emoji: '📓', keywords: ['notebook', 'journal', 'write', 'notes', 'school'] },
  { emoji: '📔', keywords: ['notebook decorated', 'journal', 'diary', 'write'] },
  { emoji: '📒', keywords: ['ledger', 'notebook', 'yellow', 'notes', 'accounts'] },
  { emoji: '📕', keywords: ['closed book', 'red', 'read', 'book', 'education'] },
  { emoji: '📗', keywords: ['green book', 'read', 'book', 'notes', 'knowledge'] },
  { emoji: '📘', keywords: ['blue book', 'read', 'book', 'study', 'knowledge'] },
  { emoji: '📙', keywords: ['orange book', 'read', 'book', 'notes'] },
  { emoji: '📚', keywords: ['books', 'library', 'read', 'study', 'knowledge', 'learn', 'stack'] },
  { emoji: '📖', keywords: ['open book', 'read', 'story', 'study', 'knowledge'] },
  { emoji: '🔖', keywords: ['bookmark', 'save', 'mark', 'reading', 'tab', 'label'] },
  { emoji: '🏷️', keywords: ['label', 'tag', 'price', 'sticker', 'mark', 'name'] },
  { emoji: '💰', keywords: ['money bag', 'rich', 'cash', 'wealth', 'dollar', 'coins'] },
  { emoji: '💴', keywords: ['yen', 'japanese', 'money', 'currency', 'japan'] },
  { emoji: '💵', keywords: ['dollar', 'usd', 'money', 'cash', 'usa', 'currency'] },
  { emoji: '💶', keywords: ['euro', 'money', 'currency', 'europe', 'eur'] },
  { emoji: '💷', keywords: ['pound', 'money', 'currency', 'uk', 'gbp', 'british'] },
  { emoji: '💳', keywords: ['credit card', 'payment', 'bank', 'finance', 'visa', 'swipe'] },
  { emoji: '🪙', keywords: ['coin', 'money', 'currency', 'gold', 'round', 'cents'] },
  { emoji: '💹', keywords: ['chart yen', 'market', 'stock', 'trade', 'green'] },
  { emoji: '📧', keywords: ['email', 'mail', 'message', 'inbox', 'send', 'letter', 'at'] },
  { emoji: '📨', keywords: ['incoming envelope', 'email', 'mail', 'receive', 'letter'] },
  { emoji: '📩', keywords: ['outgoing envelope', 'email', 'send', 'mail', 'letter'] },
  { emoji: '📤', keywords: ['outbox', 'send', 'upload', 'out', 'deliver', 'outgoing'] },
  { emoji: '📥', keywords: ['inbox', 'receive', 'download', 'in', 'incoming', 'mail'] },
  { emoji: '📦', keywords: ['package', 'box', 'delivery', 'parcel', 'ship', 'order'] },
  { emoji: '📫', keywords: ['closed mailbox', 'mail', 'post', 'letter', 'receive'] },
  { emoji: '📪', keywords: ['empty mailbox', 'mail', 'post', 'letter', 'empty'] },
  { emoji: '📬', keywords: ['open mailbox', 'mail', 'post', 'flag', 'receive'] },
  { emoji: '📭', keywords: ['open empty mailbox', 'mail', 'post', 'empty'] },
  { emoji: '📮', keywords: ['post box', 'mail', 'uk', 'red', 'post'] },
  { emoji: '🗳️', keywords: ['ballot box', 'vote', 'election', 'democracy', 'check'] },
  { emoji: '✏️', keywords: ['pencil', 'write', 'edit', 'draw', 'sketch', 'yellow'] },
  { emoji: '✒️', keywords: ['pen', 'nib', 'write', 'ink', 'sign', 'calligraphy'] },
  { emoji: '🖊️', keywords: ['pen', 'write', 'sign', 'edit', 'blue'] },
  { emoji: '🖋️', keywords: ['fountain pen', 'write', 'ink', 'elegant', 'sign'] },
  { emoji: '🖌️', keywords: ['paintbrush', 'art', 'paint', 'brush', 'draw', 'creative'] },
  { emoji: '🖍️', keywords: ['crayon', 'colour', 'draw', 'art', 'wax', 'kids'] },
  { emoji: '📐', keywords: ['triangular ruler', 'measure', 'angle', 'geometry', 'design'] },
  { emoji: '📏', keywords: ['straight ruler', 'measure', 'line', 'length', 'metric'] },
  { emoji: '🔭', keywords: ['telescope', 'space', 'stars', 'astronomy', 'look', 'explore'] },
  { emoji: '🔬', keywords: ['microscope', 'science', 'lab', 'biology', 'research', 'tiny'] },
  { emoji: '🧬', keywords: ['dna', 'genetics', 'biology', 'science', 'helix', 'gene'] },
  { emoji: '🧪', keywords: ['test tube', 'science', 'lab', 'chemistry', 'experiment', 'flask'] },
  { emoji: '🧫', keywords: ['petri dish', 'science', 'lab', 'biology', 'culture'] },
  { emoji: '🧲', keywords: ['magnet', 'attract', 'pull', 'metal', 'science', 'stick'] },
  { emoji: '🪄', keywords: ['magic wand', 'magic', 'trick', 'wizard', 'spell', 'sparkle'] },
  { emoji: '🔮', keywords: ['crystal ball', 'predict', 'magic', 'fortune', 'future', 'psychic'] },
  { emoji: '🪬', keywords: ['hamsa', 'protection', 'hand', 'evil eye', 'amulet'] },
  { emoji: '🧿', keywords: ['evil eye', 'nazar', 'protect', 'blue', 'amulet', 'ward'] },
  { emoji: '🎁', keywords: ['gift', 'present', 'wrap', 'birthday', 'surprise', 'box'] },
  { emoji: '🎀', keywords: ['ribbon', 'bow', 'gift', 'pink', 'pretty', 'wrap'] },
  { emoji: '🎊', keywords: ['confetti ball', 'celebrate', 'party', 'pop', 'colorful'] },
  { emoji: '🎈', keywords: ['balloon', 'party', 'celebrate', 'red', 'float', 'birthday'] },
  { emoji: '🎆', keywords: ['fireworks', 'celebrate', 'new year', 'explosion', 'colorful'] },
  { emoji: '🎇', keywords: ['sparkler', 'firework', 'celebrate', 'bright', 'shine'] },
  { emoji: '🧨', keywords: ['firecracker', 'bang', 'celebrate', 'chinese new year', 'red'] },
  { emoji: '🪔', keywords: ['diya lamp', 'diwali', 'light', 'indian', 'oil lamp', 'candle'] },
  { emoji: '🪅', keywords: ['pinata', 'candy', 'party', 'hit', 'mexico', 'celebrate'] },
  { emoji: '🎏', keywords: ['carp streamer', 'japanese', 'koinobori', 'celebration', 'fish'] },
  { emoji: '🎠', keywords: ['carousel', 'fairground', 'merry go round', 'ride', 'fun'] },
  { emoji: '🎡', keywords: ['ferris wheel', 'carnival', 'fairground', 'ride', 'fun'] },
  { emoji: '🎢', keywords: ['roller coaster', 'thrilling', 'ride', 'fun', 'amusement'] },
  // Symbols & signs
  { emoji: '✅', keywords: ['check', 'done', 'yes', 'correct', 'complete', 'tick', 'approved', 'green'] },
  { emoji: '❌', keywords: ['cross', 'no', 'wrong', 'incorrect', 'x', 'cancel', 'delete', 'error'] },
  { emoji: '⛔', keywords: ['no entry', 'stop', 'forbidden', 'blocked', 'red', 'ban'] },
  { emoji: '🚫', keywords: ['prohibited', 'no', 'ban', 'forbidden', 'circle slash', 'blocked'] },
  { emoji: '🚳', keywords: ['no bikes', 'cycle forbidden', 'sign', 'ban'] },
  { emoji: '🚭', keywords: ['no smoking', 'cigarette banned', 'sign', 'health'] },
  { emoji: '🚷', keywords: ['no pedestrians', 'person banned', 'sign'] },
  { emoji: '⚠️', keywords: ['warning', 'caution', 'alert', 'danger', 'triangle', 'careful'] },
  { emoji: '⚡', keywords: ['lightning', 'electric', 'fast', 'bolt', 'energy', 'power', 'zap'] },
  { emoji: '♻️', keywords: ['recycle', 'green', 'eco', 'environment', 'reuse', 'sustainable'] },
  { emoji: '✔️', keywords: ['check', 'correct', 'done', 'tick', 'yes', 'ok', 'approved'] },
  { emoji: '➕', keywords: ['plus', 'add', 'positive', 'more', 'increase', 'addition', 'cross', 'extra'] },
  { emoji: '➖', keywords: ['minus', 'subtract', 'less', 'reduce', 'negative', 'remove', 'decrease'] },
  { emoji: '✖️', keywords: ['multiply', 'times', 'cross', 'cancel', 'x', 'wrong', 'close'] },
  { emoji: '➗', keywords: ['divide', 'division', 'split', 'math', 'fraction'] },
  { emoji: '🟰', keywords: ['equals', 'equal', 'same', 'math', 'result', 'balance'] },
  { emoji: '♾️', keywords: ['infinity', 'forever', 'endless', 'loop', 'infinite'] },
  { emoji: '💲', keywords: ['dollar sign', 'money', 'currency', 'price', 'cost', 'usd'] },
  { emoji: '💱', keywords: ['exchange', 'currency', 'convert', 'money', 'rate'] },
  { emoji: '💯', keywords: ['100', 'perfect', 'score', 'hundred', 'great', 'full marks'] },
  { emoji: '🔢', keywords: ['numbers', '1234', 'count', 'input', 'digits'] },
  { emoji: '🔣', keywords: ['symbols', 'signs', 'characters', 'input'] },
  { emoji: '🔡', keywords: ['lowercase', 'letters', 'alphabet', 'abcd', 'text'] },
  { emoji: '🔠', keywords: ['uppercase', 'capital letters', 'abc', 'text'] },
  { emoji: '🆗', keywords: ['ok', 'okay', 'correct', 'approved', 'fine', 'good'] },
  { emoji: '🆙', keywords: ['up', 'upgrade', 'increase', 'better', 'improve'] },
  { emoji: '🆕', keywords: ['new', 'fresh', 'update', 'added', 'recent'] },
  { emoji: '🆓', keywords: ['free', 'no cost', 'gratis', 'complimentary'] },
  { emoji: '🆒', keywords: ['cool', 'nice', 'great', 'awesome', 'fresh'] },
  { emoji: '🆖', keywords: ['ng', 'no good', 'bad', 'wrong', 'fail', 'not good'] },
  { emoji: '🆘', keywords: ['sos', 'help', 'emergency', 'danger', 'rescue', 'save'] },
  { emoji: '🔴', keywords: ['red circle', 'stop', 'danger', 'alert', 'live', 'dot'] },
  { emoji: '🟠', keywords: ['orange circle', 'dot', 'caution', 'medium'] },
  { emoji: '🟡', keywords: ['yellow circle', 'dot', 'warning', 'caution', 'sun'] },
  { emoji: '🟢', keywords: ['green circle', 'dot', 'go', 'online', 'safe', 'active'] },
  { emoji: '🔵', keywords: ['blue circle', 'dot', 'calm', 'info', 'cool'] },
  { emoji: '🟣', keywords: ['purple circle', 'dot', 'violet', 'royal'] },
  { emoji: '⚫', keywords: ['black circle', 'dot', 'dark', 'off', 'offline'] },
  { emoji: '⚪', keywords: ['white circle', 'dot', 'blank', 'empty', 'clean'] },
  { emoji: '🔶', keywords: ['orange diamond', 'shape', 'large', 'warning', 'caution'] },
  { emoji: '🔷', keywords: ['blue diamond', 'shape', 'large', 'cool'] },
  { emoji: '🔸', keywords: ['small orange diamond', 'shape', 'dot', 'bullet'] },
  { emoji: '🔹', keywords: ['small blue diamond', 'shape', 'dot', 'bullet'] },
  { emoji: '🔺', keywords: ['red triangle up', 'arrow', 'increase', 'up', 'warning'] },
  { emoji: '🔻', keywords: ['red triangle down', 'arrow', 'decrease', 'down', 'reduce'] },
  { emoji: '💠', keywords: ['diamond blue', 'shape', 'sparkle', 'currency'] },
  { emoji: '🔘', keywords: ['radio button', 'select', 'option', 'dot', 'circle'] },
  { emoji: '🔲', keywords: ['black square button', 'button', 'black', 'square', 'box'] },
  { emoji: '🔳', keywords: ['white square button', 'button', 'white', 'square', 'box'] },
  { emoji: '▶️', keywords: ['play', 'start', 'run', 'video', 'forward', 'begin'] },
  { emoji: '⏸️', keywords: ['pause', 'stop', 'wait', 'hold', 'freeze'] },
  { emoji: '⏹️', keywords: ['stop', 'end', 'halt', 'square', 'finish'] },
  { emoji: '⏺️', keywords: ['record', 'circle', 'live', 'dot', 'button'] },
  { emoji: '⏭️', keywords: ['skip', 'next', 'fast forward', 'double arrow', 'jump'] },
  { emoji: '⏮️', keywords: ['previous', 'back', 'rewind', 'restart', 'jump'] },
  { emoji: '⏩', keywords: ['fast forward', 'skip', 'speed', 'arrows', 'next'] },
  { emoji: '⏪', keywords: ['rewind', 'back', 'previous', 'arrows', 'fast'] },
  { emoji: '🔀', keywords: ['shuffle', 'random', 'mix', 'arrows', 'crossings'] },
  { emoji: '🔁', keywords: ['repeat', 'loop', 'refresh', 'cycle', 'again'] },
  { emoji: '🔂', keywords: ['repeat once', 'loop one', 'single repeat', 'song'] },
  { emoji: '🔃', keywords: ['clockwise arrows', 'refresh', 'reload', 'sync', 'rotate'] },
  { emoji: '🔄', keywords: ['counterclockwise', 'refresh', 'reload', 'sync', 'cycle', 'update'] },
  // Arrows
  { emoji: '⬆️', keywords: ['up arrow', 'above', 'north', 'direction', 'increase', 'upload'] },
  { emoji: '⬇️', keywords: ['down arrow', 'below', 'south', 'direction', 'decrease', 'download'] },
  { emoji: '⬅️', keywords: ['left arrow', 'back', 'west', 'direction', 'previous'] },
  { emoji: '➡️', keywords: ['right arrow', 'forward', 'east', 'direction', 'next'] },
  { emoji: '↩️', keywords: ['return', 'back', 'undo', 'reply', 'revert', 'left'] },
  { emoji: '↪️', keywords: ['forward', 'redo', 'right', 'arrow', 'return'] },
  { emoji: '🔙', keywords: ['back arrow', 'return', 'backwards', 'previous', 'undo'] },
  { emoji: '🔚', keywords: ['end arrow', 'last', 'finish', 'stop'] },
  { emoji: '🔛', keywords: ['on arrow', 'active', 'switch on', 'enabled'] },
  { emoji: '🔜', keywords: ['soon arrow', 'coming', 'upcoming', 'future', 'next'] },
  { emoji: '🔝', keywords: ['top arrow', 'up', 'best', 'scroll top', 'highest'] },
  // Misc important
  { emoji: '📢', keywords: ['loudspeaker', 'announce', 'shout', 'broadcast', 'loud', 'megaphone'] },
  { emoji: '📣', keywords: ['megaphone', 'cheer', 'announce', 'loud', 'shout', 'bullhorn'] },
  { emoji: '📯', keywords: ['postal horn', 'horn', 'noise', 'announce', 'blow'] },
  { emoji: '🔔', keywords: ['bell', 'alert', 'notification', 'ring', 'alarm', 'ding'] },
  { emoji: '🔕', keywords: ['bell off', 'mute', 'silent', 'no notification', 'quiet'] },
  { emoji: '🔇', keywords: ['mute', 'silent', 'quiet', 'no sound', 'speaker off'] },
  { emoji: '🔈', keywords: ['speaker low', 'quiet', 'sound', 'volume low'] },
  { emoji: '🔉', keywords: ['speaker medium', 'sound', 'volume', 'medium'] },
  { emoji: '🔊', keywords: ['speaker loud', 'volume', 'high', 'sound', 'audio', 'noise'] },
  { emoji: '📢', keywords: ['megaphone', 'loud', 'announce', 'public', 'broadcast'] },
  { emoji: '⭐', keywords: ['star', 'favourite', 'great', 'gold', 'rating', 'shiny', 'best'] },
  { emoji: '🌟', keywords: ['glowing star', 'amazing', 'shine', 'bright', 'glow', 'sparkle'] },
  { emoji: '💫', keywords: ['dizzy star', 'spin', 'sparkle', 'dazed', 'star', 'magic'] },
  { emoji: '🎯', keywords: ['target', 'bullseye', 'aim', 'goal', 'dart', 'accurate', 'precision', 'focus'] },
  { emoji: '🏁', keywords: ['chequered flag', 'finish', 'race', 'done', 'complete', 'end', 'winning'] },
  { emoji: '🚩', keywords: ['red flag', 'warning', 'problem', 'issue', 'mark', 'signal'] },
  { emoji: '🏳️', keywords: ['white flag', 'surrender', 'peace', 'give up', 'done'] },
  { emoji: '🏴', keywords: ['black flag', 'pirate', 'dark', 'end'] },
  { emoji: '🏳️‍🌈', keywords: ['rainbow flag', 'pride', 'lgbtq', 'gay', 'inclusive', 'diversity'] },
  { emoji: '🎌', keywords: ['crossed flags', 'japan', 'celebration', 'japanese'] },
  // Time
  { emoji: '⌚', keywords: ['watch', 'time', 'clock', 'wrist', 'hours', 'minutes'] },
  { emoji: '⏰', keywords: ['alarm clock', 'wake up', 'time', 'morning', 'alert', 'ring'] },
  { emoji: '⏱️', keywords: ['stopwatch', 'timer', 'time', 'fast', 'countdown', 'race'] },
  { emoji: '⏳', keywords: ['hourglass', 'time', 'wait', 'countdown', 'sand', 'timer'] },
  { emoji: '⌛', keywords: ['hourglass done', 'time up', 'done', 'finished', 'expired'] },
  { emoji: '🕐', keywords: ['one oclock', 'time', 'clock', 'hour', 'one'] },
  { emoji: '🕧', keywords: ['twelve thirty', 'time', 'clock', 'half past'] },
  { emoji: '📅', keywords: ['calendar', 'date', 'schedule', 'event', 'plan', 'appointment'] },
  { emoji: '📆', keywords: ['tear off calendar', 'date', 'schedule', 'event', 'day'] },
  { emoji: '🗓️', keywords: ['spiral calendar', 'date', 'schedule', 'plan', 'weeks'] },
  // Health & body
  { emoji: '💊', keywords: ['pill', 'medicine', 'drug', 'medication', 'health', 'tablet'] },
  { emoji: '💉', keywords: ['syringe', 'injection', 'vaccine', 'blood', 'medical', 'shot'] },
  { emoji: '🩺', keywords: ['stethoscope', 'doctor', 'medical', 'health', 'listen', 'checkup'] },
  { emoji: '🩹', keywords: ['bandage', 'plaster', 'hurt', 'wound', 'fix', 'heal'] },
  { emoji: '🧠', keywords: ['brain', 'smart', 'think', 'mind', 'intelligence', 'memory'] },
  { emoji: '🦷', keywords: ['tooth', 'dental', 'teeth', 'dentist', 'brush'] },
  { emoji: '🦴', keywords: ['bone', 'skeleton', 'dog', 'strong', 'calcium'] },
  { emoji: '👁️', keywords: ['eye', 'look', 'see', 'watch', 'vision', 'observe'] },
  { emoji: '🫀', keywords: ['heart organ', 'cardiac', 'love', 'pulse', 'anatomy', 'beat'] },
  { emoji: '🫁', keywords: ['lungs', 'breathe', 'air', 'respiratory', 'organ'] },
  { emoji: '🧬', keywords: ['dna', 'genetics', 'helix', 'biology', 'gene', 'science'] },
  // Zodiac & symbols
  { emoji: '♈', keywords: ['aries', 'zodiac', 'ram', 'star sign', 'march april'] },
  { emoji: '♉', keywords: ['taurus', 'zodiac', 'bull', 'star sign', 'april may'] },
  { emoji: '♊', keywords: ['gemini', 'zodiac', 'twins', 'star sign', 'may june'] },
  { emoji: '♋', keywords: ['cancer', 'zodiac', 'crab', 'star sign', 'june july'] },
  { emoji: '♌', keywords: ['leo', 'zodiac', 'lion', 'star sign', 'july august'] },
  { emoji: '♍', keywords: ['virgo', 'zodiac', 'star sign', 'august september'] },
  { emoji: '♎', keywords: ['libra', 'zodiac', 'scales', 'balance', 'star sign', 'september october'] },
  { emoji: '♏', keywords: ['scorpio', 'zodiac', 'scorpion', 'star sign', 'october november'] },
  { emoji: '♐', keywords: ['sagittarius', 'zodiac', 'arrow', 'star sign', 'november december'] },
  { emoji: '♑', keywords: ['capricorn', 'zodiac', 'goat', 'star sign', 'december january'] },
  { emoji: '♒', keywords: ['aquarius', 'zodiac', 'water', 'star sign', 'january february'] },
  { emoji: '♓', keywords: ['pisces', 'zodiac', 'fish', 'star sign', 'february march'] },
  // Religion & culture
  { emoji: '☮️', keywords: ['peace', 'harmony', 'no war', 'symbol', 'hippy'] },
  { emoji: '✝️', keywords: ['cross', 'christian', 'religion', 'church', 'faith', 'latin cross'] },
  { emoji: '☪️', keywords: ['crescent star', 'muslim', 'islam', 'religion', 'faith'] },
  { emoji: '🕉️', keywords: ['om', 'hindu', 'religion', 'spiritual', 'yoga', 'meditation'] },
  { emoji: '✡️', keywords: ['star of david', 'jewish', 'judaism', 'religion', 'faith'] },
  { emoji: '☯️', keywords: ['yin yang', 'balance', 'harmony', 'taoist', 'duality'] },
  { emoji: '☢️', keywords: ['radioactive', 'nuclear', 'danger', 'radiation', 'hazard'] },
  { emoji: '☣️', keywords: ['biohazard', 'danger', 'hazard', 'toxic', 'biology', 'warning'] },
  // Misc favourites
  { emoji: '🎉', keywords: ['party', 'celebrate', 'celebration', 'tada', 'confetti', 'hooray', 'cheer'] },
  { emoji: '🥳', keywords: ['party face', 'celebrate', 'birthday', 'congrats', 'woohoo', 'hurray'] },
  { emoji: '🎊', keywords: ['confetti ball', 'celebrate', 'party', 'pop', 'colorful', 'new year'] },
  { emoji: '🚀', keywords: ['rocket', 'launch', 'fast', 'ship', 'space', 'ship it', 'deploy'] },
  { emoji: '💡', keywords: ['idea', 'light bulb', 'tip', 'insight', 'bright', 'illuminate', 'brilliant'] },
  { emoji: '🛑', keywords: ['stop sign', 'halt', 'no', 'red', 'traffic', 'blocked'] },
  { emoji: '📌', keywords: ['pin', 'pinned', 'bookmark', 'important', 'note', 'mark', 'location'] },
  { emoji: '🔍', keywords: ['magnify', 'search', 'zoom', 'find', 'look', 'examine', 'glass'] },
  { emoji: '🔎', keywords: ['magnify right', 'search', 'zoom', 'find', 'examine', 'investigate'] },
  { emoji: '📢', keywords: ['announce', 'loud', 'speaker', 'broadcast', 'shout'] },
  { emoji: '💬', keywords: ['speech bubble', 'comment', 'chat', 'message', 'talk', 'say', 'dialogue'] },
  { emoji: '💭', keywords: ['thought bubble', 'thinking', 'idea', 'dream', 'ponder', 'imagine'] },
  { emoji: '🗯️', keywords: ['anger bubble', 'angry', 'shout', 'comic', 'mad', 'yell'] },
  { emoji: '💤', keywords: ['zzz', 'sleep', 'tired', 'rest', 'quiet', 'boring', 'asleep'] },
  { emoji: '🔞', keywords: ['no under 18', 'adult only', 'restricted', 'age', 'mature', '18'] },
  { emoji: '🔐', keywords: ['locked key', 'secure', 'private', 'locked with key'] },
  { emoji: '🛡️', keywords: ['shield', 'protect', 'defense', 'security', 'guard', 'safe'] },
  { emoji: '⚔️', keywords: ['swords', 'crossed', 'battle', 'fight', 'war', 'weapon'] },
  { emoji: '🗡️', keywords: ['dagger', 'knife', 'weapon', 'stab', 'blade'] },
  { emoji: '🪃', keywords: ['boomerang', 'return', 'throw', 'come back', 'australia'] },
  { emoji: '🏹', keywords: ['bow arrow', 'shoot', 'aim', 'archery', 'target', 'cupid'] },
  { emoji: '🪤', keywords: ['mouse trap', 'trap', 'catch', 'snap', 'trick'] },
  { emoji: '🪣', keywords: ['bucket', 'container', 'water', 'pail', 'carry'] },
  { emoji: '🧲', keywords: ['magnet', 'attract', 'pull', 'metal', 'science', 'stick'] },
  { emoji: '🪜', keywords: ['ladder', 'climb', 'step', 'reach', 'up', 'stairs'] },
  { emoji: '🧰', keywords: ['toolbox', 'tools', 'fix', 'repair', 'build', 'kit', 'maintenance'] },
  { emoji: '🧴', keywords: ['lotion', 'bottle', 'skincare', 'cream', 'soap', 'pump'] },
  { emoji: '🧹', keywords: ['broom', 'sweep', 'clean', 'witch', 'floor', 'tidy'] },
  { emoji: '🧺', keywords: ['basket', 'laundry', 'carry', 'shopping', 'wicker'] },
  { emoji: '🧻', keywords: ['toilet paper', 'roll', 'tissue', 'bathroom', 'wipe'] },
  { emoji: '🪣', keywords: ['bucket', 'water', 'container', 'mop', 'clean'] },
  { emoji: '🧼', keywords: ['soap', 'clean', 'wash', 'lather', 'hygiene', 'bubble'] },
  { emoji: '🧽', keywords: ['sponge', 'clean', 'wash', 'absorb', 'scrub'] },
  { emoji: '🪥', keywords: ['toothbrush', 'teeth', 'brush', 'dental', 'clean', 'morning'] },
  { emoji: '🧴', keywords: ['lotion', 'moisturizer', 'skincare', 'bottle', 'pump'] },
  { emoji: '🚿', keywords: ['shower', 'wash', 'clean', 'bathroom', 'water', 'refresh'] },
  { emoji: '🛁', keywords: ['bath', 'tub', 'relax', 'wash', 'soak', 'bathroom'] },
  { emoji: '🪞', keywords: ['mirror', 'reflect', 'look', 'vanity', 'glass', 'see'] },
  { emoji: '🪟', keywords: ['window', 'glass', 'view', 'open', 'frame', 'light'] },
  { emoji: '🛏️', keywords: ['bed', 'sleep', 'rest', 'tired', 'bedroom', 'hotel'] },
  { emoji: '🛋️', keywords: ['couch', 'sofa', 'relax', 'sit', 'lounge', 'furniture'] },
  { emoji: '🚪', keywords: ['door', 'open', 'close', 'enter', 'exit', 'room'] },
  { emoji: '🪑', keywords: ['chair', 'sit', 'seat', 'furniture', 'office', 'rest'] },
  { emoji: '🗑️', keywords: ['trash', 'bin', 'rubbish', 'delete', 'waste', 'garbage', 'can'] },
  { emoji: '🎓', keywords: ['graduation', 'cap', 'graduate', 'education', 'degree', 'university', 'student'] },
  { emoji: '🏫', keywords: ['school', 'education', 'building', 'class', 'study'] },
  { emoji: '📐', keywords: ['ruler', 'angle', 'measure', 'geometry', 'triangle', 'design'] },
  { emoji: '🌐', keywords: ['globe', 'web', 'internet', 'world', 'network', 'online', 'global'] },
  { emoji: '🔗', keywords: ['link', 'chain', 'connect', 'url', 'hyperlink', 'attach', 'web'] },
  { emoji: '📊', keywords: ['bar chart', 'graph', 'data', 'analytics', 'statistics', 'report'] },
  { emoji: '📈', keywords: ['trending up', 'growth', 'increase', 'profit', 'stocks', 'up', 'rise'] },
  { emoji: '📉', keywords: ['trending down', 'decline', 'loss', 'decrease', 'stocks', 'fall'] },
  { emoji: '🧑‍💻', keywords: ['programmer', 'developer', 'coder', 'engineer', 'tech', 'computer'] },
  { emoji: '🧑‍🎨', keywords: ['artist', 'designer', 'creative', 'painter', 'draw'] },
  { emoji: '💼', keywords: ['briefcase', 'work', 'business', 'job', 'office', 'professional'] },
  { emoji: '🗞️', keywords: ['newspaper', 'news', 'read', 'headline', 'press', 'media'] },
  { emoji: '📰', keywords: ['newspaper', 'news', 'read', 'article', 'press', 'media', 'journal'] },
  { emoji: '🔑', keywords: ['key', 'unlock', 'access', 'password', 'login', 'open'] },
  { emoji: '🌮', keywords: ['taco', 'mexican', 'food', 'wrap', 'tuesday'] },
  { emoji: '☕', keywords: ['coffee', 'morning', 'cafe', 'hot drink', 'mug', 'caffeine', 'brew'] },
  { emoji: '🍕', keywords: ['pizza', 'food', 'cheese', 'slice', 'italian', 'yummy'] },
  { emoji: '🎯', keywords: ['target', 'goal', 'aim', 'bullseye', 'focus', 'hit', 'accurate'] },
  { emoji: '💎', keywords: ['diamond', 'gem', 'precious', 'jewel', 'sparkle', 'rich', 'luxury'] },
  { emoji: '👑', keywords: ['crown', 'king', 'queen', 'royal', 'best', 'top', 'winner'] },
  { emoji: '🌴', keywords: ['palm', 'tropical', 'beach', 'vacation', 'holiday', 'sun', 'island'] },
  { emoji: '🌊', keywords: ['wave', 'ocean', 'surf', 'water', 'sea', 'beach'] },
  { emoji: '🎸', keywords: ['guitar', 'rock', 'music', 'band', 'play', 'string', 'instrument'] },
  { emoji: '🧩', keywords: ['puzzle', 'piece', 'fit', 'solve', 'connect', 'jigsaw', 'missing'] },
  { emoji: '🃏', keywords: ['joker', 'card', 'wild', 'game', 'playing card', 'trump'] },
  { emoji: '🀄', keywords: ['mahjong', 'game', 'tile', 'chinese', 'red dragon'] },
  { emoji: '🎴', keywords: ['flower playing card', 'hanafuda', 'japanese', 'game', 'card'] },
  { emoji: '🧸', keywords: ['teddy bear', 'toy', 'soft', 'cute', 'plush', 'child', 'hug'] },
  { emoji: '🪆', keywords: ['nesting doll', 'matryoshka', 'russian', 'toy', 'dolls'] },
  { emoji: '🧿', keywords: ['evil eye', 'nazar', 'protect', 'charm', 'blue', 'bead'] },
  { emoji: '🎐', keywords: ['wind chime', 'japanese', 'wind', 'sound', 'bell', 'summer'] },
  { emoji: '🎑', keywords: ['moon viewing', 'japanese', 'autumn', 'celebration', 'rabbit'] },
  { emoji: '🎃', keywords: ['halloween', 'pumpkin', 'jack o lantern', 'scary', 'spooky', 'october'] },
  { emoji: '🎄', keywords: ['christmas', 'xmas', 'tree', 'holiday', 'festive', 'december'] },
  { emoji: '🎋', keywords: ['tanabata', 'bamboo', 'japanese', 'wish', 'festival'] },
  { emoji: '🎍', keywords: ['pine decoration', 'new year', 'japanese', 'fresh', 'bamboo'] },
  { emoji: '🧧', keywords: ['red envelope', 'lucky money', 'chinese new year', 'gift', 'luck'] },
  { emoji: '🎎', keywords: ['japanese dolls', 'hina', 'festival', 'decoration', 'celebration'] },
  { emoji: '🎏', keywords: ['carp streamer', 'koinobori', 'japanese', 'wind', 'boys day'] },
  { emoji: '🎁', keywords: ['gift', 'present', 'birthday', 'surprise', 'wrapped', 'box', 'give'] },
  { emoji: '🧨', keywords: ['firecracker', 'bang', 'loud', 'new year', 'chinese', 'red', 'celebration'] },
  { emoji: '🛍️', keywords: ['shopping bag', 'shop', 'buy', 'retail', 'purchase', 'fashion'] },
  { emoji: '🪤', keywords: ['trap', 'catch', 'snap', 'spring', 'clever'] },
  { emoji: '🧲', keywords: ['magnet', 'attract', 'pull', 'stick', 'science', 'metal', 'force'] },
  { emoji: '🌡️', keywords: ['thermometer', 'temperature', 'hot', 'cold', 'fever', 'measure'] },
  { emoji: '🔭', keywords: ['telescope', 'stars', 'space', 'astronomy', 'look far', 'explore'] },
  { emoji: '🔬', keywords: ['microscope', 'science', 'tiny', 'lab', 'biology', 'small', 'zoom'] },
  { emoji: '⚗️', keywords: ['alembic', 'chemistry', 'lab', 'experiment', 'science', 'potion'] },
  { emoji: '🧪', keywords: ['test tube', 'chemistry', 'experiment', 'lab', 'science', 'liquid'] },
  { emoji: '💊', keywords: ['pill', 'tablet', 'medicine', 'drug', 'health', 'pharmacy'] },
  { emoji: '💉', keywords: ['syringe', 'needle', 'vaccine', 'injection', 'medical', 'blood'] },
  { emoji: '🩸', keywords: ['blood', 'drop', 'donate', 'red', 'medical', 'health'] },
  { emoji: '🩹', keywords: ['bandage', 'plaster', 'hurt', 'healing', 'cut', 'fix', 'wound'] },
  { emoji: '🩺', keywords: ['stethoscope', 'doctor', 'listen', 'heartbeat', 'medical', 'diagnose'] },
  { emoji: '🚬', keywords: ['cigarette', 'smoke', 'tobacco', 'bad habit', 'nicotine'] },
  { emoji: '⚰️', keywords: ['coffin', 'death', 'funeral', 'buried', 'RIP', 'casket'] },
  { emoji: '🪦', keywords: ['headstone', 'grave', 'RIP', 'death', 'burial'] },
  { emoji: '⚱️', keywords: ['urn', 'ash', 'memorial', 'funeral', 'cremation'] },
  // More people expressions
  { emoji: '🫡', keywords: ['salute', 'respect', 'yes sir', 'roger', 'honour'] },
  { emoji: '🫥', keywords: ['dotted face', 'invisible', 'absent', 'hidden', 'blank'] },
  { emoji: '🤡', keywords: ['clown', 'joke', 'circus', 'funny', 'foolish', 'scary'] },
  { emoji: '💃', keywords: ['dance', 'dancing', 'woman', 'salsa', 'party', 'move'] },
  { emoji: '🕺', keywords: ['dance', 'man', 'disco', 'party', 'move', 'groove'] },
  { emoji: '🧘', keywords: ['meditate', 'yoga', 'lotus', 'calm', 'peace', 'zen', 'mindful'] },
  { emoji: '🏋️', keywords: ['weightlifting', 'gym', 'strong', 'fitness', 'exercise', 'lift'] },
  { emoji: '🚴', keywords: ['cycling', 'bike', 'bicycle', 'sport', 'exercise', 'race'] },
  { emoji: '🏊', keywords: ['swimming', 'pool', 'water', 'sport', 'exercise', 'dive'] },
  { emoji: '🤾', keywords: ['handball', 'throw', 'sport', 'jump', 'ball'] },
  { emoji: '🧗', keywords: ['climbing', 'rock', 'wall', 'adventure', 'sport', 'mountain'] },
  { emoji: '🏄', keywords: ['surfing', 'wave', 'ocean', 'sport', 'beach', 'cool'] },
  { emoji: '🤺', keywords: ['fencing', 'sword', 'sport', 'duel', 'fight'] },
  { emoji: '⛷️', keywords: ['skiing', 'snow', 'sport', 'winter', 'mountain', 'ski'] },
  { emoji: '🏂', keywords: ['snowboarding', 'snow', 'winter', 'sport', 'board'] },
  { emoji: '🤼', keywords: ['wrestling', 'fight', 'sport', 'grapple', 'opponents'] },
  { emoji: '🤸', keywords: ['gymnastics', 'flip', 'cartwheel', 'flexible', 'sport'] },
  { emoji: '⛹️', keywords: ['bouncing ball', 'basketball', 'sport', 'dribble', 'player'] },
  { emoji: '🏌️', keywords: ['golf', 'swing', 'sport', 'club', 'course', 'green'] },
  { emoji: '🏇', keywords: ['horse racing', 'jockey', 'race', 'fast', 'sport'] },
  { emoji: '🏆', keywords: ['trophy', 'winner', 'champion', 'award', 'first place', 'best', 'gold cup'] },
  { emoji: '🎪', keywords: ['circus', 'tent', 'performance', 'show', 'entertainment'] },
  { emoji: '🎭', keywords: ['masks', 'theatre', 'drama', 'performance', 'comedy', 'tragedy', 'show'] },
  { emoji: '🤿', keywords: ['diving mask', 'scuba', 'snorkel', 'underwater', 'ocean', 'swim'] },
  { emoji: '🎣', keywords: ['fishing', 'fish', 'rod', 'patience', 'catch', 'lake'] },
  { emoji: '🏕️', keywords: ['camping', 'tent', 'outdoor', 'forest', 'nature', 'wild'] },
  { emoji: '🌁', keywords: ['fog', 'mist', 'foggy', 'bridge', 'san francisco', 'grey'] },
  { emoji: '🌫️', keywords: ['fog', 'mist', 'cloud', 'unclear', 'hazy', 'grey'] },
]

interface EmojiPickerPortalProps {
  anchorRef: React.RefObject<HTMLElement | null>
  onSelect: (emoji: string) => void
  onClose: () => void
}

export function EmojiPickerPortal({ anchorRef, onSelect, onClose }: EmojiPickerPortalProps) {
  const [search, setSearch] = useState('')
  const [pos, setPos] = useState({ top: 0, left: 0 })
  const pickerRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (anchorRef.current) {
      const rect = anchorRef.current.getBoundingClientRect()
      const pickerH = 280
      const pickerW = 272
      const top = rect.top - pickerH - 6 < 8 ? rect.bottom + 6 : rect.top - pickerH - 6
      const left = Math.min(rect.left, window.innerWidth - pickerW - 8)
      setPos({ top, left })
    }
    setTimeout(() => inputRef.current?.focus(), 0)
  }, [anchorRef])

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (pickerRef.current && !pickerRef.current.contains(e.target as Node) &&
          anchorRef.current && !anchorRef.current.contains(e.target as Node)) {
        onClose()
      }
    }
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('mousedown', handleClick)
    document.addEventListener('keydown', handleKey)
    return () => {
      document.removeEventListener('mousedown', handleClick)
      document.removeEventListener('keydown', handleKey)
    }
  }, [anchorRef, onClose])

  const query = search.trim().toLowerCase()
  const filtered = query
    ? EMOJIS.filter(({ emoji, keywords }) =>
        keywords.some((k) => k.includes(query)) || emoji.includes(query)
      )
    : EMOJIS

  const picker = (
    <div
      ref={pickerRef}
      style={{
        position: 'fixed',
        top: pos.top,
        left: pos.left,
        zIndex: 2147483648,
        width: 272,
        background: '#fff',
        border: '1px solid #e5e7eb',
        borderRadius: 12,
        boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
        padding: 10,
        fontFamily: 'system-ui, sans-serif',
      }}
    >
      <input
        ref={inputRef}
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        placeholder="Search emoji…"
        style={{
          width: '100%',
          marginBottom: 8,
          padding: '5px 10px',
          fontSize: 12,
          border: '1px solid #e5e7eb',
          borderRadius: 6,
          outline: 'none',
          boxSizing: 'border-box',
        }}
      />
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 2, maxHeight: 200, overflowY: 'auto' }}>
        {filtered.map(({ emoji, keywords }) => (
          <button
            key={emoji}
            onClick={() => { onSelect(emoji); onClose() }}
            title={keywords[0]}
            style={{
              width: 36,
              height: 36,
              fontSize: 20,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              background: 'none',
              border: 'none',
              borderRadius: 6,
              cursor: 'pointer',
              padding: 0,
            }}
            onMouseEnter={(e) => (e.currentTarget.style.background = '#f3f4f6')}
            onMouseLeave={(e) => (e.currentTarget.style.background = 'none')}
          >
            {emoji}
          </button>
        ))}
        {filtered.length === 0 && (
          <span style={{ fontSize: 12, color: '#9ca3af', padding: '4px 2px' }}>No results</span>
        )}
      </div>
    </div>
  )

  return createPortal(picker, document.body)
}
